version: "3"

services:
  rightmove-commute-api:
    image: mattcroberts/rightmove-commute:${RIGHTMOVE_COMMUTE_TAG}
    restart: on-failure
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    ports:
      - "6000:6000"
    expose:
      - 6000
